SillyStringz/Models/Engineer.cs
using System.Collections.Generic;


namespace Stringz.Models
{
  public class Engineer
  {
    public string Name { get; set; }
    public int EngineerId { get; set; }

    public List<EngineerMachine> JoinEntities {get; set; }

    public Engineer()
    {
      JoinEntities = new List<EngineerMachine>();
    }
  }
}

SillyStringz/Models/EngineerMachine.cs
namespace Stringz.Models
{
  public class EngineerMachine
  {
    public Engineer Engineer {get; set; }
    public Machine Machine { get; set; }

    public int EngineerId { get; set; }
    public int MachineId { get; set; }

    public int EngineerMachineId {get; set;}
  }
}

SillyStringz/Models/ErrorViewModel.cs
namespace SillyStringz.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

SillyStringz/Models/Machine.cs
using System.Collections.Generic;


namespace Stringz.Models
{
  public class Machine
  {
    public int MachineId { get; set; }
    public string Name { get; set; }
  

    public List<EngineerMachine> Engineers { get; set; }

    public Machine()
    {
      Engineers = new List<EngineerMachine>();
    }
  }
}

SillyStringz/Models/StringzContext.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using Stringz.Models;

namespace Stringz.Models
{
  public class StringzContext : DbContext
  {

    public DbSet<EngineerMachine> EngineerMachines { get; set; }
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }



    public StringzContext(DbContextOptions<StringzContext> options) : base(options) { }

    protected override void OnModelCreating(ModelBuilder modelBuilder)//doing this explicitly because i was having issues with workbench
    {
      base.OnModelCreating(modelBuilder);

      modelBuilder.Entity<EngineerMachine>() //PK for engineermachines
        .HasKey(em => em.EngineerMachineId);

      //many to many
      modelBuilder.Entity<EngineerMachine>()
    .HasOne(em => em.Engineer)
    .WithMany(e => e.JoinEntities)
    .HasForeignKey(em => em.EngineerId)
    .OnDelete(DeleteBehavior.Cascade);//so that deleting an engineer doesn't break stuff

      modelBuilder.Entity<EngineerMachine>()
    .HasOne(em => em.Machine)
    .WithMany(m => m.Engineers)
    .HasForeignKey(em => em.MachineId)
    .OnDelete(DeleteBehavior.Cascade);
    }
  }
}

SillyStringz/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stringz.Models;
using System.Collections.Generic;
using System.Linq;

namespace Stringz.Controllers
{
  public class EngineersController : Controller
  {
    private readonly StringzContext _db;

    public EngineersController(StringzContext db)
    {
      _db = db;
    }
    public IActionResult Index()
    {
      var engineers = _db.Engineers
                          .Include(e => e.JoinEntities)
                          .ThenInclude(je => je.Machine)
                          .ToList();
      return View(engineers);
    }
    public IActionResult Details(int? id)
    {
      Engineer engineer = _db.Engineers
          .Include(e => e.JoinEntities)
          .ThenInclude(je => je.Machine)
          .FirstOrDefault(m => m.EngineerId == id);

      return View(engineer);
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(Engineer engineer)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");

    }


    public IActionResult Edit(int id)
    {
      Engineer engineer = _db.Engineers.Include(e => e.JoinEntities).FirstOrDefault(e => e.EngineerId == id);

      return View(engineer);
    }


    [HttpPost]

    public IActionResult Edit(Engineer engineer)
    {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Delete(int id)
    {
      Engineer engineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public IActionResult AddMachine(int id)
    {
      var engineer = _db.Engineers.Find(id);
      if (engineer == null)
      {
        return NotFound();
      }

      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(engineer);
    }

    [HttpPost]
    public IActionResult AddMachine(int id, [FromForm] int machineId)
    {
      var engineer = _db.Engineers.Find(id);
      if (engineer == null)
      {
        return NotFound();
      }

      var existingAssignment = _db.EngineerMachines.Any(em => em.EngineerId == id && em.MachineId == machineId);
      if (!existingAssignment)
      {
        _db.EngineerMachines.Add(new EngineerMachine { EngineerId = id, MachineId = machineId });
        _db.SaveChanges();
      }

      return RedirectToAction("Details", new { id = id });
    }
  }
}

SillyStringz/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Stringz.Models;

namespace SillyStringz.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

SillyStringz/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stringz.Models;
using System.Linq;

namespace Stringz.Controllers
{
  public class MachinesController : Controller
  {
    private readonly StringzContext _db;

    public MachinesController(StringzContext db)
    {
      _db = db;
    }

    public IActionResult Index()
    {
      return View(_db.Machines.ToList());
    }

    public IActionResult Details(int? id)
    {
      Machine machine = _db.Machines
          .Include(m => m.Engineers)
          .ThenInclude(je => je.Engineer)
          .FirstOrDefault(e => e.MachineId == id);

      return View(machine);
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public IActionResult Edit(int id)
    {
      Machine machine = _db.Machines.Find(id);
      return View(machine);
    }

    [HttpPost]
    public IActionResult Edit(Machine machine)
    {
      _db.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Delete(int id)
    {
      Machine machine = _db.Machines.Find(id);

      _db.Machines.Remove(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

SillyStringz/Views/Engineer/Detail.cshtml
@model Stringz.Models.Engineer

<!DOCTYPE html>
<html>
<head>
    <title>Engineer Details</title>
    <link href="~/css/EngineerDetails.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <h2>Engineer Details</h2>
    <div>
        <h4>Engineer</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>@Html.DisplayFor(model => model.Name)</dd>
        </dl>
    </div>
    @using (Html.BeginForm("Delete", "Engineers", new { id = Model.EngineerId }, FormMethod.Post))
    {
        <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this?');" />
    }
    @Html.ActionLink("Edit", "Edit", new { id = Model.EngineerId }) |
    @Html.ActionLink("Back to List", "Index")
</body>
</html>

SillyStringz/Views/Engineer/Index.cshtml
@model IEnumerable<Stringz.Models.Engineer>

<!DOCTYPE html>
<html>
<head>
    <title>Engineers</title>
    <link href="~/css/EngineerIndex.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <h2>Engineers</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var engineer in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => engineer.Name)</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = engineer.EngineerId }) |
                        @Html.ActionLink("Details", "Details", new { id = engineer.EngineerId })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @Html.ActionLink("Add New Engineer", "Create")
</body>
</html>

SillyStringz/Views/Engineers/AddMachine.cshtml
@model Stringz.Models.Engineer

@{
    ViewData["Title"] = "Add Machine to Engineer";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="text-center">@ViewData["Title"]</h2>
                <h4>Engineer: @Html.DisplayFor(model => model.Name)</h4>
                <hr />
                @using (Html.BeginForm("AddMachine", "Engineers", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {                        
                    @Html.HiddenFor(model => model.EngineerId)
                    
                    <div class="form-group">
                        <label for="MachineId" class="control-label">Select Machine:</label>
                        @Html.DropDownList("MachineId", null, "-- Select a Machine --", new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Add Machine" class="btn btn-primary" />
                    </div>
                }

                <div>
                    @Html.ActionLink("Back to Engineer Details", "Details", new { id = Model.EngineerId }, new { @class = "btn btn-secondary" })
                </div>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

SillyStringz/Views/Engineers/Create.cshtml
@model Stringz.Models.Engineer

<!DOCTYPE html>
<html>
<head>
    <title>Add Engineer</title>
   <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
</head>
<body>
    <h2>Add an Engineer</h2>
    @using (Html.BeginForm())
    {
        <p>@Html.LabelFor(model => model.Name): @Html.TextBoxFor(model => model.Name, new {@required = "required"})</p>
        <input name="submit" type="submit" value="Submit" />
    }
    @Html.ActionLink("Go back to Engineers", "Index")
</body>
</html>

SillyStringz/Views/Engineers/Details.cshtml
@model Stringz.Models.Engineer

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
    <title>Engineer Details</title>
</head>
<body>
    <h2>Engineer Details</h2>
    <div>
        <h4>Engineer</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>@Html.DisplayFor(model => model.Name)</dd>
        </dl>
    </div>
    
    <div>
        <h4>Associated Machines</h4>
        <ul>
            @foreach(var machine in Model.JoinEntities.Select(je => je.Machine))
            {
                <li>@Html.DisplayFor(_ => machine.Name)</li>
            }
        </ul>
    </div>

    @using (Html.BeginForm("Delete", "Engineers", new { id = Model.EngineerId }, FormMethod.Post))
    {
        <input type="submit" value="Delete" onclick="return confirm('Are you sure you want to delete this?');" />
    }
    @Html.ActionLink("Edit", "Edit", new { id = Model.EngineerId }) |
    @Html.ActionLink("Back to List", "Index")
</body>
</html>

SillyStringz/Views/Engineers/Edit.cshtml
@model Stringz.Models.Engineer

<!DOCTYPE html>
<html>

<head>
    <title>Edit Engineer</title>
    <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
</head>

<body>
    <h2>Edit Engineer</h2>
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.EngineerId)
        <p>@Html.LabelFor(model => model.Name): @Html.TextBoxFor(model => model.Name, new { @required = "required" })</p>
        <input name="submit" type="submit" value="Update" />
    }
    <p>
        @Html.ActionLink("Add Machine", "AddMachine", new { id = Model.EngineerId }) |
        @Html.ActionLink("Go back to Engineers", "Index")
    </p>
</body>

</html>

SillyStringz/Views/Engineers/Index.cshtml
@model IEnumerable<Stringz.Models.Engineer>
@using Stringz.Models

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
    <title>Engineers</title>
</head>
<body>
    <h2>Engineers</h2>

    @foreach (Engineer engineer in Model)
    {
        <div>
            <h3>@Html.DisplayFor(_ => engineer.Name)</h3>
            <p><strong>Associated Machines:</strong></p>
            <ul>
                @foreach (var joinEntity in engineer.JoinEntities)
                {
                    <li>@joinEntity.Machine.Name</li>
                }
            </ul>
            @Html.ActionLink("Edit", "Edit", new { id = engineer.EngineerId }, new { @class = "action-link" }) |
            @Html.ActionLink("Details", "Details", new { id = engineer.EngineerId }, new { @class = "action-link" })
        </div>
    }

    @Html.ActionLink("Add New Engineer", "Create", null, new { @class = "add-new-link" })

    <p>Machines:</p>
    @Html.ActionLink("View machine index", "Index", "Machines")
</body>
</html>

SillyStringz/Views/Home/Index.cshtml
@using Stringz.Models

<link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
<div class="text-center">
    <h1 class="display-4">Welcome to SillyStringz Factory</h1>
    <p>Create, edit, delete or assign an engineer</p>

    @Html.ActionLink("View engineer index", "Index", "Engineers")
    <p>Create, edit, delete or assign a machine</p>

    @Html.ActionLink("View machine index", "Index", "Machines")


</div>

SillyStringz/Views/Machines/Create.cshtml
@model Stringz.Models.Machine
@using Stringz.Models

<!DOCTYPE html>
<html>
<head>
    <title>Create Machine</title>
   <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
</head>
<body>
    <h2>Create a New Machine</h2>
    @using (Html.BeginForm())
    {
        <p>@Html.LabelFor(model => model.Name): @Html.TextBoxFor(model => model.Name, new {@required = "required"})</p>
        <input type="submit" value="Create" />
    }
    @Html.ActionLink("Back to List", "Index")
</body>
</html>

SillyStringz/Views/Machines/Details.cshtml
@model Stringz.Models.Machine
@using Stringz.Models

<!DOCTYPE html>
<html>
<head>
    <title>Machine Details</title>
  <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
</head>
<body>
    <h2>Machine Details</h2>
    <div>
        <h4>Machine</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>Name</dt>
            <dd>@Html.DisplayFor(model => model.Name)</dd>
        </dl>
    </div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MachineId }) |
    @Html.ActionLink("Back to List", "Index")
</body>
</html>

SillyStringz/Views/Machines/Edit.cshtml
@model Stringz.Models.Machine
@using Stringz.Models

<!DOCTYPE html>
<html>
<head>
    <title>Edit Machine</title>
   <link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
</head>
<body>
    <h2>Edit Machine</h2>
    @using (Html.BeginForm("Edit", "Machines", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.MachineId)
        <p>@Html.LabelFor(model => model.Name): @Html.TextBoxFor(model => model.Name, new {@required = "required"})</p>
        <input type="submit" value="Update" />
    }


    @using (Html.BeginForm("Delete", "Machines", new { id = Model.MachineId }, FormMethod.Post, true, htmlAttributes: new { @class = "delete-form" }))
    {        
        <input type="submit" value="Delete" class="btn btn-danger" />
    }
    
    @Html.ActionLink("Back to List", "Index", null, new { @class = "back-link" })
</body>
</html>

SillyStringz/Views/Machines/Index.cshtml
@model IEnumerable<Stringz.Models.Machine>
@using Stringz.Models

<!DOCTYPE html>
<html>
<head>
    <title>Machines</title>
<link rel="stylesheet" href="~/css/SillyStringz.styles.css" asp-append-version="true" />
</head>
<body>
    <h2>Machines</h2>

    @foreach (Machine machine in Model)
    {
        <div>
            <h3>@Html.DisplayFor(modelItem => machine.Name)</h3>
            <p><strong>Associated Engineers:</strong></p>
            <ul>
                @foreach (var joinEntity in machine.Engineers)
                {
                    <li>@Html.DisplayFor(_ => joinEntity.Engineer.Name)</li>
                }
            </ul>
            @Html.ActionLink("Edit", "Edit", new { id = machine.MachineId }, new { @class = "action-link" }) |
            @Html.ActionLink("Details", "Details", new { id = machine.MachineId }, new { @class = "action-link" })
        </div>
    }

    @Html.ActionLink("Add New Machine", "Create", null, new { @class = "add-new-link" })

    <p>Engineers:</p>
    @Html.ActionLink("View engineer index", "Index", "Engineers")
</body>
</html>

SillyStringz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SillyStringz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SillyStringz.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SillyStringz</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Engineers"
                                asp-action="Index">Engineers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Machines"
                                asp-action="Index">Machines</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <h4>SillyStringz Factory</h4>
            <p>&copy; 2024 - All rights reserved.</p>
            @Html.ActionLink("Home", "Index", "Home", new { @class = "footer-home-link" })
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>